services:
    postgresdb:
        image: postgres:latest
        container_name: postgresql-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin # Remplacez par le nom d'utilisateur souhaité
            POSTGRES_PASSWORD: adminpwd # Remplacez par le mot de passe souhaité
            POSTGRES_DB: db # Remplacez par le nom de la base de données souhaité
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d db"]
            interval: 10s
            timeout: 5s
            retries: 10
        restart: always

    server:
        container_name: spice-world-api
        build:
            context: .
            dockerfile: ./apps/server/Dockerfile
        ports:
            - "3001:3001"
        depends_on:
            - postgresdb
        environment:
            DATABASE_URL: postgresql://admin:adminpwd@postgresdb:5432/db
            UPLOADTHING_TOKEN: ${UPLOADTHING_TOKEN}
            BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
            BETTER_AUTH_URL: http://localhost:3000
            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
            RESEND_API_KEY: ${RESEND_API_KEY}
        restart: always
